### ISSUE TITLE
寻找原始API

### ISSUE THREAD

**Issue by zhangzonghong** [XiangGuo1992/Screen-Vehicle-Detection-using-Tensorflow-API#13]
博主，目前的tensorflow 的目标检测API变化很大，你能给我一份您写这篇博客的原始API吗，谢谢

**Comment by XiangGuo1992** [comment]
现在的版本变化挺大的，我之前用的是API 1.4版本，视频里的是1.7, 当然用以前的也可以，但是我建议用最新的，性能、兼容性上可能更好一些。我这一系列教程用来额外参考。

**Comment by zhangzonghong** [comment]
博主，我按照你的视频教程对最新版的API进行了配置，D:\tensorflow-model\models\research\object_detection>python model_main.py \ --pipeline_config_path=object_detection/training/ssd_mobilenet_v1_coco.config \  --model_dir=object_detection/training \  --num_train_steps=50000 \ --num_eval_steps=2000 \ --alsologtostderr

但是最后的结果变成了这样，我一直没找到解决方案：
Traceback (most recent call last):
  File "model_main.py", line 109, in <module>
    tf.app.run()
  File "D:\Users\45104\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "model_main.py", line 71, in main
    FLAGS.sample_1_of_n_eval_on_train_examples))
  File "D:\tensorflow-model\models\research\object_detection\model_lib.py", line 617, in create_estimator_and_inputs
    pipeline_config_path, config_override=config_override)
  File "D:\tensorflow-model\models\research\object_detection\utils\config_util.py", line 103, in get_configs_from_pipeline_file
    proto_str = f.read()
  File "D:\Users\45104\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 125, in read
    self._preread_check()
  File "D:\Users\45104\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "D:\Users\45104\Anaconda3\envs\Tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: object_detection/training/ssd_mobilenet_v1_coco.config : ϵͳ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4·\udcbe\udcb6\udca1\udca3
; No such process

望提供下解决方案

**Comment by XiangGuo1992** [comment]
object_detection/training/ssd_mobilenet_v1_coco.config
查看一下这个目录下是否有这个配置文件
