### ISSUE TITLE
大神，我又来请教你了。

### ISSUE THREAD

**Issue by shallwerain** [XiangGuo1992/Screen-Vehicle-Detection-using-Tensorflow-API#5]
由于我的笔记本性能不够做各种实验。
于是换了一个台式。
但是在台式机上搭建环境时碰到了问题，具体如下：
       搭建环境是参照你的博客，之前的步骤没有差错，但是在最后一步时：
       在 models/research/ 文件夹下运行命令行：python object_detection/builders/model_builder_test.py
       出现了以下错误：
----------------------------------------------<分割线>---------------------------------------------------
Microsoft Windows [版本 10.0.17134.48]
(c) 2018 Microsoft Corporation。保留所有权利。

G:\objectD\models-master\research>python object_detection/builders/model_builder_test.py
G:\ProgramData\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
EEEEEEEE.EEEEE.
======================================================================
ERROR: test_create_embedded_ssd_mobilenet_v1_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 515, in test_create_embedded_ssd_mobilenet_v1_model_from_config
    model = self.create_model(model_proto)
  File "object_detection/builders/model_builder_test.py", line 69, in create_model
    return model_builder.build(model_config, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 98, in build
    add_background_class)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 166, in _build_ssd_model
    is_training=is_training)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 129, in _build_ssd_feature_extractor
    feature_extractor_config.override_base_feature_extractor_hyperparams)
AttributeError: 'SsdFeatureExtractor' object has no attribute 'override_base_feature_extractor_hyperparams'

======================================================================
ERROR: test_create_faster_rcnn_inception_resnet_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 859, in test_create_faster_rcnn_inception_resnet_v2_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
    add_summaries)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
    num_classes=num_classes)
  File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
    mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'

======================================================================
ERROR: test_create_faster_rcnn_inception_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 926, in test_create_faster_rcnn_inception_v2_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
    add_summaries)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
    num_classes=num_classes)
  File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
    mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'

======================================================================
ERROR: test_create_faster_rcnn_model_from_config_with_example_miner (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 984, in test_create_faster_rcnn_model_from_config_with_example_miner
    model = model_builder.build(model_proto, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
    add_summaries)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
    num_classes=num_classes)
  File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
    mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'

======================================================================
ERROR: test_create_faster_rcnn_nas_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 725, in test_create_faster_rcnn_nas_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
    add_summaries)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
    num_classes=num_classes)
  File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
    mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'

======================================================================
ERROR: test_create_faster_rcnn_pnas_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 792, in test_create_faster_rcnn_pnas_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
    add_summaries)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
    num_classes=num_classes)
  File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
    mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'

======================================================================
ERROR: test_create_faster_rcnn_resnet101_with_mask_prediction_enabled (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 661, in test_create_faster_rcnn_resnet101_with_mask_prediction_enabled
    model = model_builder.build(model_proto, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
    add_summaries)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
    num_classes=num_classes)
  File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
    mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'

======================================================================
ERROR: test_create_faster_rcnn_resnet_v1_models_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 584, in test_create_faster_rcnn_resnet_v1_models_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
    add_summaries)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
    num_classes=num_classes)
  File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
    mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'

======================================================================
ERROR: test_create_ssd_inception_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 137, in test_create_ssd_inception_v2_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 15:11 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "override_base_feature_extractor_hyperparams".

======================================================================
ERROR: test_create_ssd_inception_v3_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 209, in test_create_ssd_inception_v3_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 15:11 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "override_base_feature_extractor_hyperparams".

======================================================================
ERROR: test_create_ssd_mobilenet_v1_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 367, in test_create_ssd_mobilenet_v1_model_from_config
    text_format.Merge(model_text_proto, model_proto)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
    descriptor_pool=descriptor_pool)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
    return parser.MergeLines(lines, message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
    self._ParseOrMerge(lines, message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
    self._MergeField(tokenizer, message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
    merger(tokenizer, message, field)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
    self._MergeField(tokenizer, sub_message)
  File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 703, in _MergeField
    (message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 3:9 : Message type "object_detection.protos.Ssd" has no field named "freeze_batchnorm".

======================================================================
ERROR: test_create_ssd_mobilenet_v2_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 443, in test_create_ssd_mobilenet_v2_model_from_config
    model = self.create_model(model_proto)
  File "object_detection/builders/model_builder_test.py", line 69, in create_model
    return model_builder.build(model_config, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 98, in build
    add_background_class)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 166, in _build_ssd_model
    is_training=is_training)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 129, in _build_ssd_feature_extractor
    feature_extractor_config.override_base_feature_extractor_hyperparams)
AttributeError: 'SsdFeatureExtractor' object has no attribute 'override_base_feature_extractor_hyperparams'

======================================================================
ERROR: test_create_ssd_resnet_v1_fpn_model_from_config (__main__.ModelBuilderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 295, in test_create_ssd_resnet_v1_fpn_model_from_config
    model = model_builder.build(model_proto, is_training=True)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 98, in build
    add_background_class)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 166, in _build_ssd_model
    is_training=is_training)
  File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 129, in _build_ssd_feature_extractor
    feature_extractor_config.override_base_feature_extractor_hyperparams)
AttributeError: 'SsdFeatureExtractor' object has no attribute 'override_base_feature_extractor_hyperparams'

----------------------------------------------------------------------
Ran 15 tests in 0.051s

FAILED (errors=13)

G:\objectD\models-master\research>

----------------------------------------------<分割线>---------------------------------------------------
有一个重要的地方是，我的电脑原来装有Python.

请问这13个错误是怎么一回事，该怎么解决呢？
麻烦你了，谢谢！

**Comment by XiangGuo1992** [comment]
https://github.com/tensorflow/models/issues/4121
看这个网址，有好几个方案，你都试试


Sent from Mail for Windows 10

From: shallwerain
Sent: Sunday, May 20, 2018 7:52 AM
To: XiangGuo1992/Screen-Vehicle-Detection-using-Tensorflow-API
Cc: Subscribed
Subject: [XiangGuo1992/Screen-Vehicle-Detection-using-Tensorflow-API] 大神，我又来请教你了。 (#5)

由于我的笔记本性能不够做各种实验。
于是换了一个台式。
但是在台式机上搭建环境时碰到了问题，具体如下：
搭建环境是参照你的博客，之前的步骤没有差错，但是在最后一步时：
在 models/research/ 文件夹下运行命令行：python object_detection/builders/model_builder_test.py
出现了以下错误：
----------------------------------------------<分割线>---------------------------------------------------
Microsoft Windows [版本 10.0.17134.48]
(c) 2018 Microsoft Corporation。保留所有权利。
G:\objectD\models-master\research>python object_detection/builders/model_builder_test.py
G:\ProgramData\lib\site-packages\h5py_init_.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
from ._conv import register_converters as _register_converters
EEEEEEEE.EEEEE.
ERROR: test_create_embedded_ssd_mobilenet_v1_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 515, in test_create_embedded_ssd_mobilenet_v1_model_from_config
model = self.create_model(model_proto)
File "object_detection/builders/model_builder_test.py", line 69, in create_model
return model_builder.build(model_config, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 98, in build
add_background_class)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 166, in _build_ssd_model
is_training=is_training)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 129, in _build_ssd_feature_extractor
feature_extractor_config.override_base_feature_extractor_hyperparams)
AttributeError: 'SsdFeatureExtractor' object has no attribute 'override_base_feature_extractor_hyperparams'
======================================================================
ERROR: test_create_faster_rcnn_inception_resnet_v2_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 859, in test_create_faster_rcnn_inception_resnet_v2_model_from_config
model = model_builder.build(model_proto, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
add_summaries)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
num_classes=num_classes)
File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'
======================================================================
ERROR: test_create_faster_rcnn_inception_v2_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 926, in test_create_faster_rcnn_inception_v2_model_from_config
model = model_builder.build(model_proto, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
add_summaries)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
num_classes=num_classes)
File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'
======================================================================
ERROR: test_create_faster_rcnn_model_from_config_with_example_miner (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 984, in test_create_faster_rcnn_model_from_config_with_example_miner
model = model_builder.build(model_proto, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
add_summaries)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
num_classes=num_classes)
File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'
======================================================================
ERROR: test_create_faster_rcnn_nas_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 725, in test_create_faster_rcnn_nas_model_from_config
model = model_builder.build(model_proto, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
add_summaries)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
num_classes=num_classes)
File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'
======================================================================
ERROR: test_create_faster_rcnn_pnas_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 792, in test_create_faster_rcnn_pnas_model_from_config
model = model_builder.build(model_proto, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
add_summaries)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
num_classes=num_classes)
File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'
======================================================================
ERROR: test_create_faster_rcnn_resnet101_with_mask_prediction_enabled (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 661, in test_create_faster_rcnn_resnet101_with_mask_prediction_enabled
model = model_builder.build(model_proto, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
add_summaries)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
num_classes=num_classes)
File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'
======================================================================
ERROR: test_create_faster_rcnn_resnet_v1_models_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 584, in test_create_faster_rcnn_resnet_v1_models_from_config
model = model_builder.build(model_proto, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 101, in build
add_summaries)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 308, in _build_faster_rcnn_model
num_classes=num_classes)
File "G:\objectD\models-master\research\object_detection\builders\box_predictor_builder.py", line 117, in build
mask_rcnn_box_predictor.masks_are_class_agnostic),
AttributeError: 'MaskRCNNBoxPredictor' object has no attribute 'masks_are_class_agnostic'
======================================================================
ERROR: test_create_ssd_inception_v2_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 137, in test_create_ssd_inception_v2_model_from_config
text_format.Merge(model_text_proto, model_proto)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
descriptor_pool=descriptor_pool)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
return parser.MergeLines(lines, message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
self._ParseOrMerge(lines, message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
self._MergeField(tokenizer, message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
merger(tokenizer, message, field)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
self._MergeField(tokenizer, sub_message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
merger(tokenizer, message, field)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
self._MergeField(tokenizer, sub_message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 703, in _MergeField
(message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 15:11 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "override_base_feature_extractor_hyperparams".
======================================================================
ERROR: test_create_ssd_inception_v3_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 209, in test_create_ssd_inception_v3_model_from_config
text_format.Merge(model_text_proto, model_proto)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
descriptor_pool=descriptor_pool)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
return parser.MergeLines(lines, message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
self._ParseOrMerge(lines, message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
self._MergeField(tokenizer, message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
merger(tokenizer, message, field)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
self._MergeField(tokenizer, sub_message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
merger(tokenizer, message, field)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
self._MergeField(tokenizer, sub_message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 703, in _MergeField
(message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 15:11 : Message type "object_detection.protos.SsdFeatureExtractor" has no field named "override_base_feature_extractor_hyperparams".
======================================================================
ERROR: test_create_ssd_mobilenet_v1_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 367, in test_create_ssd_mobilenet_v1_model_from_config
text_format.Merge(model_text_proto, model_proto)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 533, in Merge
descriptor_pool=descriptor_pool)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 587, in MergeLines
return parser.MergeLines(lines, message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 620, in MergeLines
self._ParseOrMerge(lines, message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 635, in _ParseOrMerge
self._MergeField(tokenizer, message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 735, in _MergeField
merger(tokenizer, message, field)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 823, in _MergeMessageField
self._MergeField(tokenizer, sub_message)
File "G:\ProgramData\lib\site-packages\google\protobuf\text_format.py", line 703, in _MergeField
(message_descriptor.full_name, name))
google.protobuf.text_format.ParseError: 3:9 : Message type "object_detection.protos.Ssd" has no field named "freeze_batchnorm".
======================================================================
ERROR: test_create_ssd_mobilenet_v2_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 443, in test_create_ssd_mobilenet_v2_model_from_config
model = self.create_model(model_proto)
File "object_detection/builders/model_builder_test.py", line 69, in create_model
return model_builder.build(model_config, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 98, in build
add_background_class)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 166, in _build_ssd_model
is_training=is_training)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 129, in _build_ssd_feature_extractor
feature_extractor_config.override_base_feature_extractor_hyperparams)
AttributeError: 'SsdFeatureExtractor' object has no attribute 'override_base_feature_extractor_hyperparams'
======================================================================
ERROR: test_create_ssd_resnet_v1_fpn_model_from_config (main.ModelBuilderTest)
Traceback (most recent call last):
File "object_detection/builders/model_builder_test.py", line 295, in test_create_ssd_resnet_v1_fpn_model_from_config
model = model_builder.build(model_proto, is_training=True)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 98, in build
add_background_class)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 166, in _build_ssd_model
is_training=is_training)
File "G:\objectD\models-master\research\object_detection\builders\model_builder.py", line 129, in _build_ssd_feature_extractor
feature_extractor_config.override_base_feature_extractor_hyperparams)
AttributeError: 'SsdFeatureExtractor' object has no attribute 'override_base_feature_extractor_hyperparams'

Ran 15 tests in 0.051s
FAILED (errors=13)
G:\objectD\models-master\research>
----------------------------------------------<分割线>---------------------------------------------------
有一个重要的地方是，我的电脑原来装有Python.
请问这13个错误是怎么一回事，该怎么解决呢？
麻烦你了，谢谢！

**Comment by shallwerain** [comment]
感谢大神，我已成功解决问题并训练得到了不错的模型，效果也不错。
